# Generated by Django 6.0.2 on 2026-02-06 21:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='İlan Başlığı')),
                ('price', models.IntegerField(verbose_name='Fiyat')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('district', models.CharField(max_length=100, verbose_name='İlçe')),
                ('main_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Eklenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.category')),
            ],
        ),
    ]
