# Generated by Django 6.0.2 on 2026-02-06 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingDetail',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='listings.listing')),
                ('emlak_tipi', models.CharField(choices=[('Satılık', 'Satılık'), ('Kiralık', 'Kiralık')], max_length=20)),
                ('m2_brut', models.IntegerField(verbose_name='Brüt m²')),
                ('m2_net', models.IntegerField(verbose_name='Net m²')),
                ('oda_sayisi', models.CharField(choices=[('1+0', '1+0'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1', '4+1'), ('5+1', '5+1'), ('Villa', 'Villa'), ('Müstakil', 'Müstakil')], max_length=20, verbose_name='Oda Sayısı')),
                ('bina_yasi', models.IntegerField(verbose_name='Bina Yaşı')),
                ('bulundugu_kat', models.CharField(max_length=20, verbose_name='Bulunduğu Kat')),
                ('kat_sayisi', models.IntegerField(verbose_name='Kat Sayısı')),
                ('isitma', models.CharField(choices=[('Yok', 'Yok'), ('Kombi', 'Kombi'), ('Merkezi', 'Merkezi'), ('Klima', 'Klima')], max_length=20, verbose_name='Isıtma')),
                ('banyo_sayisi', models.IntegerField(verbose_name='Banyo Sayısı')),
                ('mutfak', models.CharField(choices=[('Kapalı', 'Kapalı'), ('Amerikan', 'Amerikan'), ('Açık', 'Açık')], max_length=20, verbose_name='Mutfak Tipi')),
                ('balkon', models.BooleanField(default=False, verbose_name='Balkon Var mı?')),
                ('asansor', models.BooleanField(default=False, verbose_name='Asansör Var mı?')),
                ('otopark', models.BooleanField(default=False, verbose_name='Otopark Var mı?')),
                ('esyali', models.BooleanField(default=False, verbose_name='Eşyalı mı?')),
                ('site_icerisinde', models.BooleanField(default=False, verbose_name='Site İçerisinde mi?')),
                ('site_adi', models.CharField(blank=True, max_length=100, verbose_name='Site Adı')),
                ('aidat', models.IntegerField(default=0, verbose_name='Aidat (TL)')),
            ],
        ),
        migrations.CreateModel(
            name='LandDetail',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='listings.listing')),
                ('emlak_tipi', models.CharField(choices=[('Satılık', 'Satılık'), ('Kiralık', 'Kiralık')], max_length=20)),
                ('imar_durumu', models.CharField(max_length=50, verbose_name='İmar Durumu')),
                ('m2', models.IntegerField(verbose_name='Metrekare')),
                ('m2_fiyat', models.IntegerField(verbose_name='m² Fiyatı')),
                ('ada_no', models.CharField(blank=True, max_length=50, verbose_name='Ada No')),
                ('parsel_no', models.CharField(blank=True, max_length=50, verbose_name='Parsel No')),
                ('pafta_no', models.CharField(blank=True, max_length=50, verbose_name='Pafta No')),
                ('kaks', models.CharField(blank=True, max_length=20, verbose_name='Kaks (Emsal)')),
                ('gabari', models.CharField(blank=True, max_length=20, verbose_name='Gabari')),
            ],
        ),
    ]
