# Generated by Django 6.0.2 on 2026-02-16 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_category_options_category_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingdetail',
            name='emlak_tipi',
        ),
        migrations.RemoveField(
            model_name='housingdetail',
            name='esyali',
        ),
        migrations.RemoveField(
            model_name='housingdetail',
            name='mutfak',
        ),
        migrations.RemoveField(
            model_name='housingdetail',
            name='site_adi',
        ),
        migrations.RemoveField(
            model_name='housingdetail',
            name='site_icerisinde',
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='akilli_ev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='ankastre_mutfak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='avmye_yakin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='camasir_odasi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='celik_kapi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='cocuk_parki',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='deniz_manzarasi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='dogamanzarasi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='ebeveyn_banyosu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='esya_durumu',
            field=models.CharField(choices=[('Eşyalı', 'Eşyalı'), ('Eşyasız', 'Eşyasız')], default='Eşyasız', max_length=20, verbose_name='Eşya Durumu'),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='fiber_internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='giyinme_odasi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='goruntulu_diafon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='guvenlik',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='hastaneye_yakin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='jenerator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='kiler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='krediye_uygun',
            field=models.BooleanField(default=False, verbose_name='Krediye Uygun'),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='kullanim_durumu',
            field=models.CharField(blank=True, choices=[('Boş', 'Boş'), ('Kiracılı', 'Kiracılı'), ('Mülk Sahibi', 'Mülk Sahibi')], max_length=50, verbose_name='Kullanım Durumu'),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='metrobuse_yakin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='metroya_yakin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='mutfak_tipi',
            field=models.CharField(blank=True, choices=[('Kapalı Mutfak', 'Kapalı Mutfak'), ('Amerikan Mutfak', 'Amerikan Mutfak'), ('Açık Mutfak', 'Açık Mutfak')], max_length=50),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='okula_yakin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='sehir_manzarasi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='site_icinde',
            field=models.BooleanField(default=False, verbose_name='Site İçerisinde'),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='somine',
            field=models.BooleanField(default=False, verbose_name='Şömine'),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='spor_salonu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='takas',
            field=models.BooleanField(default=False, verbose_name='Takaslı'),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='tapu_durumu',
            field=models.CharField(blank=True, choices=[('Kat Mülkiyeti', 'Kat Mülkiyeti'), ('Kat İrtifakı', 'Kat İrtifakı'), ('Arsa Tapulu', 'Arsa Tapulu'), ('Hisseli Tapu', 'Hisseli Tapu')], max_length=50),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='teras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingdetail',
            name='yuzme_havuzu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='aidat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aidat (TL)'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='asansor',
            field=models.BooleanField(default=False, verbose_name='Asansör Var'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='balkon',
            field=models.BooleanField(default=False, verbose_name='Balkon Var'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='banyo_sayisi',
            field=models.PositiveIntegerField(default=1, verbose_name='Banyo Sayısı'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='bina_yasi',
            field=models.IntegerField(default=0, verbose_name='Bina Yaşı'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='bulundugu_kat',
            field=models.CharField(max_length=50, verbose_name='Bulunduğu Kat'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='isitma',
            field=models.CharField(choices=[('Yok', 'Yok'), ('Kombi', 'Kombi'), ('Merkezi', 'Merkezi'), ('Klima', 'Klima'), ('Yerden Isıtma', 'Yerden Isıtma')], default='Yok', max_length=50, verbose_name='Isıtma Tipi'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='kat_sayisi',
            field=models.IntegerField(verbose_name='Toplam Kat Sayısı'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='housing_details', serialize=False, to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='m2_brut',
            field=models.PositiveIntegerField(verbose_name='Brüt m²'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='m2_net',
            field=models.PositiveIntegerField(verbose_name='Net m²'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='oda_sayisi',
            field=models.CharField(max_length=20, verbose_name='Oda Sayısı'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='otopark',
            field=models.CharField(choices=[('Yok', 'Yok'), ('Açık Otopark', 'Açık Otopark'), ('Kapalı Otopark', 'Kapalı Otopark'), ('Açık & Kapalı', 'Açık & Kapalı')], default='Yok', max_length=50),
        ),
    ]
