# Generated by Django 6.0.2 on 2026-02-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_housingdetail_emlak_tipi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingdetail',
            name='bulundugu_kat',
            field=models.CharField(choices=[('Bodrum Kat', 'Bodrum Kat'), ('Zemin Kat', 'Zemin Kat'), ('Bahçe Katı', 'Bahçe Katı'), ('Giriş Katı', 'Giriş Katı'), ('Yüksek Giriş', 'Yüksek Giriş'), ('Müstakil', 'Müstakil'), ('1', '1. Kat'), ('2', '2. Kat'), ('3', '3. Kat'), ('4', '4. Kat'), ('5', '5. Kat'), ('10-20 arası', '10-20. Kat arası'), ('20 ve üzeri', '20. Kat ve üzeri'), ('En Üst Kat', 'En Üst Kat')], default='Giriş Katı', max_length=50, verbose_name='Bulunduğu Kat'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='mutfak_tipi',
            field=models.CharField(blank=True, choices=[('Kapalı Mutfak', 'Kapalı Mutfak'), ('Amerikan Mutfak', 'Amerikan Mutfak'), ('Açık Mutfak', 'Açık Mutfak')], max_length=50, verbose_name='Mutfak Tipi'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='oda_sayisi',
            field=models.CharField(choices=[('1+0', '1+0 (Stüdyo)'), ('1+1', '1+1'), ('2+0', '2+0'), ('2+1', '2+1'), ('2+2', '2+2'), ('3+1', '3+1'), ('3+2', '3+2'), ('4+1', '4+1'), ('4+2', '4+2'), ('5+1', '5+1'), ('5+2', '5+2'), ('6+1', '6+1'), ('6+2', '6+2'), ('7+ ve üzeri', '7+ ve üzeri')], default='2+1', max_length=20, verbose_name='Oda Sayısı'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='otopark',
            field=models.CharField(choices=[('Yok', 'Yok'), ('Açık Otopark', 'Açık Otopark'), ('Kapalı Otopark', 'Kapalı Otopark'), ('Açık & Kapalı', 'Açık & Kapalı')], default='Yok', max_length=50, verbose_name='Otopark'),
        ),
        migrations.AlterField(
            model_name='housingdetail',
            name='tapu_durumu',
            field=models.CharField(blank=True, choices=[('Kat Mülkiyeti', 'Kat Mülkiyeti'), ('Kat İrtifakı', 'Kat İrtifakı'), ('Arsa Tapulu', 'Arsa Tapulu'), ('Hisseli Tapu', 'Hisseli Tapu')], max_length=50, verbose_name='Tapu Durumu'),
        ),
    ]
